Woods-Trevin/TripleConfirmedGames

- routes/users.js
> testing comment

- commands.md
- db/seeders/20210823213845-addGame.js
- package-lock.json
- package.json
- routes/users.js
- views/signup.pug
- views/utils.pug
> working on signup

- routes/games.js
- routes/users.js
- views/layout.pug
Please review logout, get games, and get game Id route
> finished log out, started get games and get game by Id route

- db/seeders/20210823213845-addGame.js
- db/seeders/20210823213849-addReview.js
- db/seeders/20210823213855-addSlap.js
- db/seeders/20210823213900-addShelf.js
- db/seeders/20210823213906-addReviewLike.js
- db/seeders/20210823213912-addGameCleanRating.js
- db/seeders/20210823213917-addUser.js
- routes/games.js
- views/games.pug
> finished gameList framework for posting on /games

- routes/games.js
- views/game-page.pug
- views/games.pug
> finished setting up individual routes/pages for games dynamically

- routes/games.js
- views/game-page.pug
> added reviews to be shown with user name

- routes/games.js
- views/game-page.pug
> able to create and read reviews

- routes/games.js
- routes/reviews.js
- views/game-page.pug
- views/review-edit.pug
> added edit functionality to reviews

- commands.md
- routes/users.js
- views/addShelf.pug
- views/layout.pug
- views/mygames.pug
- views/profile.pug
Added pug page for mygames libraries and populated user reviews below user profile.
> pulled resources

- db/models/shelf.js
- routes/users.js
- views/game-page.pug
> added casscade delete thingy in shelf model

- routes/index.js
now able to access splash page when not logged in
> now able to access splash page when not logged in

- public/javascripts/mygamesDOM.js
- views/mygames.pug
> made imgs with anchor links

- public/stylesheets/mygames.css
- views/layout.pug
- views/mygames.pug
Added styling to mygamespage. Floated table to right of column. added borders. Still working on getting release date to show up in correct column if there are no shelves added for game. Added black background to table. Working on styling add and delete buttons.
> added styling to mygamespage

- public/stylesheets/mygames.css
- views/mygames.pug
added styling to add shelf and delete shelf buttons. Going to format profile page next. If anyone has any ideas on how to fill the shelves column for games that dont have a shelf. Right now im going to change over to profile page.
> fixed buttons on mygamespage

- public/stylesheets/addShelf.css
- public/stylesheets/deleteShelf.css
- public/stylesheets/mygames.css
- views/addShelf.pug
- views/deleteShelf.pug
- views/layout.pug
Fixed issue where background styling from mygames spilled over to paths of btns
> added styling to paths from my games page btns

- public/stylesheets/mygames.css
- views/mygames.pug
Fixed table column issue where no shelf is displayed if the game wasn't added to shelf. Clean.
> fixed issue with table column not displaying value

- public/stylesheets/mygames.css
> fixed table in mygames page

- public/stylesheets/browseGames.css
- public/stylesheets/index.css
- views/games.pug
> added browsegames.css, changed default text to black

- public/stylesheets/gamePage.css
- public/stylesheets/splash.css
- views/game-page.pug
- views/layout.pug
> Cssgamepage

- public/stylesheets/browseGames.css
- routes/games.js
- views/games.pug
> added more to browse games page

- public/stylesheets/profile.css
- views/profile.pug
Added pink colors to headers and fixed a media query issue with the lines between each game
> Finished UserProfile page & small fixes

- public/stylesheets/browseGames.css
> the games POP now

- views/game-page.pug
- views/layout.pug
> fixed log in error

- public/stylesheets/mygames.css
- public/stylesheets/profile.css
- views/mygames.pug
- views/profile.pug
Solved bug with mygames page. Kind of a strange fix but everything is still viewable.
> solved bug with mygames page

- db/models/gamejoin.js
- public/stylesheets/mygames.css
- routes/games.js
- routes/users.js
- views/games.pug
- views/mygames.pug
My games page adds game to base page when MyGames nav is clicked and Game was added to a shelf on individual game page. Also added CSS to table on my games page to expand image and title of games to show a user that they can click that element.
> fixed bug with mygames tables and added css to some elements on mygames table

- public/javascripts/mygamesDOM.js
- routes/users.js
My games page adds game to base page when MyGames nav is clicked and Game was added to a shelf on individual game page. Also added CSS to table on my games page to expand image and title of games to show a user that they can click that element. Fixed bug where shelves were clicked and image was a different size. Added hover functionality to tables rendered based on shelves.
> added functionality to mygames table

- public/stylesheets/browseGames.css
- public/stylesheets/mygames.css
- public/stylesheets/profile.css
- views/games.pug
- views/mygames.pug
- views/profile.pug
> added more css to my games and profile page

- public/stylesheets/gamePage.css
- routes/users.js
- views/mygames.pug
- views/profile.pug
pair programming with rawaha and trevin
> working on dom for mygames

- public/stylesheets/mygames.css
> heroku fix with arnold and basel pair programming

- public/stylesheets/mygames.css
- public/stylesheets/nav.css
- views/addShelf.pug
- views/mygames.pug
pair prog with basel and rawaha
> fixed up some buttons

- public/stylesheets/addShelf.css
- public/stylesheets/deleteShelf.css
- public/stylesheets/textArea.css
- views/addShelf.pug
- views/deleteShelf.pug
- views/game-page.pug
- views/layout.pug
- views/profile.pug
- views/review-delete.pug
- views/review-edit.pug
> touched up some buttons and add/ edit/delete pages with basel

- public/stylesheets/gamePage.css
- public/stylesheets/textArea.css
- views/game-page.pug
> added more touchups to game reviews

- routes/games.js
- views/game-page.pug
> fixing error right before class with basel
